=== wiswis15/CordisProject/WebApplication1/BackendConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>
  <xs:element name="configuration">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="server"/>
        <xs:element ref="variable" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="server">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="address" type="xs:string"/>
        <xs:element name="port" type="xs:integer"/>
        <xs:element name="path" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="variable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="controllername" type="xs:string"/>
        <xs:element name="machinename" type="xs:string"/>
        <xs:element name="machinepart" type="xs:string"/>
        <xs:element name="observername" type="xs:string"/>
        <xs:element name="interval" type="xs:integer"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== wiswis15/CordisProject/MCDBackend/TestBackendConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation='BackendConfig.xsd'>
    <server>
        <address>123.45.67.89</address>
        <port>321</port>
        <path>Test/path.with.dots/</path>
    </server>
    <variable>
        <controllername>TestControllerName</controllername>
        <machinename>TestMachineName</machinename>
        <machinepart>TestMachinePart</machinepart>
        <observername>TestObserverName</observername>
        <interval>12345</interval>
    </variable>
</configuration>

=== wiswis15/CordisProject/WebApplication1/BackendConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation='BackendConfig.xsd'>
    <server>
        <address>127.0.0.1</address>
        <port>8080</port>
        <path>JsonServices/com.cordis.explorer.connectors.MachinePart.MachinePartConnector</path>
    </server>
    <variable>
        <controllername>BeckhoffOPC</controllername>
        <machinename>Machine</machinename>
        <machinepart>ObserverTesterA</machinepart>
        <!-- Observername: BoolVar, FloatVar, EnumVar, Int32Var, StringVar or Int64Var -->
        <observername>FloatVar</observername>
        <interval>2000</interval>
    </variable>
    <variable>
        <controllername>BeckhoffOPC</controllername>
        <machinename>Machine</machinename>
        <machinepart>ObserverTesterB</machinepart>
        <!-- Observername: BoolVar, FloatVar, EnumVar, Int32Var, StringVar or Int64Var -->
        <observername>BoolVar</observername>
        <interval>2500</interval>
    </variable>
</configuration>
